async function buildRoute(){if(!st.parking){await loadData();if(!st.parking)return}stopNavigation();clearRoute();const start=st.user||st.dest,candidates=rankSegments();if(!candidates.length)return note('No parking curbs match those filters.',6000);st.route=orderSegments(candidates,+$('count').value,start);if(!st.route.length)return note('No drivable parking route could be built.');st.route.forEach((x,i)=>{const m=new maplibregl.Marker({element:markerEl('marker-num',String(i+1))}).setLngLat([x.m.lng,x.m.lat]).addTo(map);st.numberMarkers.push(m)});const pts=[start,...st.route.flatMap(x=>[x.entry,x.exit])],lines=[];for(let i=0;i<pts.length-1;i+=17){const chunk=pts.slice(i,Math.min(i+18,pts.length));if(chunk.length<2)continue;try{lines.push(await routeRequest(chunk))}catch(e){note(`Routing fallback used: ${e.message}`,3500);lines.push({geometry:{type:'LineString',coordinates:chunk.map(p=>[p.lng,p.lat])}})}}const merged=mergeLines(lines);setRouteGeo(merged);fitRoute(merged);renderRouteList();updateCurrentCurb();$('start').disabled=$('next').disabled=$('found').disabled=false;$('routeStat').textContent=`${st.route.length} curbs`;note(st.user?'Route starts at your GPS location.':'Route built around the destination; GPS is required to navigate.')}
function nearestInstruction(r){return r?.maneuvers?.find(m=>m.type!==1&&m.length>0.01)||r?.maneuvers?.[0]}
function speak(text){if(!$('voice').checked||!text||text===st.lastSpoken||!('speechSynthesis'in window))return;st.lastSpoken=text;speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.rate=1.02;speechSynthesis.speak(u)}
async function liveRoute(force=false){if(!st.navigating||!st.user||!st.route.length)return;const now=Date.now();if(!force&&now-st.lastRouteAt<5500)return;st.lastRouteAt=now;const x=st.route[st.idx],dEntry=hav(st.user,x.entry),dExit=hav(st.user,x.exit),scanning=dEntry<55;const pts=scanning?[st.user,x.exit]:[st.user,x.entry,x.exit];try{const r=await routeRequest(pts);setRouteGeo({type:'Feature',properties:{},geometry:r.geometry});const m=nearestInstruction(r);if(scanning){const text=`Scan ${nameOf(x.f)} for parking`;$('navMain').textContent=text;$('navSub').textContent=`${Math.max(0,Math.round(dExit*3.28084))} ft to end · segment ${st.idx+1}/${st.route.length}`;if(dEntry<40)speak(text);if(dExit<28)advance(true)}else{const text=m?.instruction||`Continue to ${nameOf(x.f)}`;$('navMain').textContent=text;$('navSub').textContent=`${Math.max(1,Math.round((r.summary?.time||0)/60))} min · then scan ${nameOf(x.f)}`;speak(text)}if(st.navigating){const bearing=st.user.heading??map.getBearing();map.easeTo({center:[st.user.lng,st.user.lat],zoom:17.8,pitch:58,bearing,duration:700})}}catch(e){$('navMain').textContent=`Continue to ${nameOf(x.f)}`;$('navSub').textContent=`Routing temporarily unavailable · ${Math.round(dEntry*3.28084)} ft to curb`}}
async function startNavigation(){if(!st.route.length)await buildRoute();if(!st.route.length)return;if(!st.user)try{await requestGPS(false)}catch{return}st.navigating=true;$('navcard').classList.add('show');$('start').disabled=true;if(st.watch!==null)navigator.geolocation.clearWatch(st.watch);st.watch=navigator.geolocation.watchPosition(p=>{updateUser(p);liveRoute()},()=>{}, {enableHighAccuracy:true,maximumAge:800,timeout:15000});updateCurrentCurb();liveRoute(true)}
function stopNavigation(){st.navigating=false;if(st.watch!==null&&navigator.geolocation)navigator.geolocation.clearWatch(st.watch);st.watch=null;$('navcard').classList.remove('show');if(st.route.length)$('start').disabled=false}
function advance(auto=false){if(!st.route.length)return;if(st.idx<st.route.length-1){st.idx++;updateCurrentCurb();st.lastSpoken='';if(st.navigating)liveRoute(true)}else{if(!auto)note('End of this search route. Increase the scan count and rebuild.',6000);else{stopNavigation();note('Reached the end of the parking search route.',6000)}}}
function foundSpot(){const x=st.route[st.idx];stopNavigation();speechSynthesis?.cancel?.();note(`Parking found near ${x?nameOf(x.f):'current location'}. Verify the posted signs before leaving the vehicle.`,8000)}
async function geocode(q){return getJSON('/api/geocode?q='+encodeURIComponent(q))}
async function submitDestination(e){e.preventDefault();const q=$('dest').value.trim();if(!q)return;try{const g=await geocode(q);st.dest={lat:g.lat,lng:g.lng,label:g.label};setDestinationMarker();clearRoute();map.easeTo({center:[g.lng,g.lat],zoom:16,pitch:0,bearing:0,duration:900});note(`Destination: ${g.label}`)}catch(e){note(`Destination search failed: ${e.message}`,6000)}}

map.on('load',()=>{st.mapReady=true;addDataLayers();setDestinationMarker();refreshMapData()});
$('destForm').addEventListener('submit',submitDestination);
$('gps').addEventListener('click',()=>requestGPS(true).catch(()=>{}));
$('find').addEventListener('click',buildRoute);
$('start').addEventListener('click',startNavigation);
$('next').addEventListener('click',()=>advance(false));
$('found').addEventListener('click',foundSpot);
$('recenter').addEventListener('click',()=>st.user?map.easeTo({center:[st.user.lng,st.user.lat],zoom:17.8,pitch:st.navigating?58:35,bearing:st.navigating?(st.user.heading??map.getBearing()):0,duration:700}):requestGPS(true).catch(()=>{}));
['zone','free','permit','paid','count'].forEach(id=>$(id).addEventListener('change',()=>{stopNavigation();clearRoute();refreshMapData()}));
if(!window.isSecureContext)note('Live GPS requires HTTPS. Use the Vercel deployment URL.',7000);
loadData();