const $=id=>document.getElementById(id);
const INF={lat:29.64865,lng:-82.33535,label:'Infinity Hall'};
const COLORS={free:'#2caf76',permit:'#a989ff',paid:'#3478f6',timed:'#f2bd49',mixed:'#f29c55',no:'#ef646d'};
const st={dest:INF,parking:null,zones:null,route:[],idx:0,user:null,watch:null,userMarker:null,destMarker:null,numberMarkers:[],navigating:false,lastRouteAt:0,lastSpoken:'',mapReady:false,routeGeometry:null,navGeometry:null};
let noteTimer;

const map=new maplibregl.Map({container:'map',style:'https://tiles.openfreemap.org/styles/liberty',center:[INF.lng,INF.lat],zoom:15,pitch:0,bearing:0,attributionControl:true});
map.addControl(new maplibregl.NavigationControl({visualizePitch:true}),'bottom-right');

function note(msg,ms=4000){$('notice').textContent=msg;$('notice').classList.add('show');clearTimeout(noteTimer);noteTimer=setTimeout(()=>$('notice').classList.remove('show'),ms)}
function low(v){return String(v??'').toLowerCase()}
function hav(a,b){const R=6371000,p=Math.PI/180,dlat=(b.lat-a.lat)*p,dlon=(b.lng-a.lng)*p,x=Math.sin(dlat/2)**2+Math.cos(a.lat*p)*Math.cos(b.lat*p)*Math.sin(dlon/2)**2;return 2*R*Math.asin(Math.sqrt(x))}
function coords(f){const g=f?.geometry;if(!g)return[];return g.type==='LineString'?g.coordinates:g.type==='MultiLineString'?g.coordinates.flat():[]}
function midpoint(f){const c=coords(f);if(!c.length)return null;let x=0,y=0;for(const p of c){x+=p[0];y+=p[1]}return{lng:x/c.length,lat:y/c.length}}
function endpoints(f){const c=coords(f);if(!c.length)return null;return{a:{lng:c[0][0],lat:c[0][1]},b:{lng:c.at(-1)[0],lat:c.at(-1)[1]}}}
function nameOf(f){const p=f.properties||{};return p.location_1||p.segmentlab||p.location||p.street||'Street parking'}
function zoneFromProps(p={}){const preferred=['permitzone','permit_zone','zone','zone_no','zone_num','zonenumber','enforczone'];const entries=Object.entries(p),vals=[];for(const want of preferred){for(const [k,v] of entries){if(k.toLowerCase().replace(/[^a-z0-9]/g,'')===want.replace(/[^a-z0-9]/g,''))vals.push(v)}}for(const [k,v] of entries)if(k.toLowerCase().includes('zone'))vals.push(v);for(const v of vals){const m=String(v??'').match(/(?:zone\s*)?(1|2|6|7|8|12)(?:\D|$)/i);if(m)return m[1]}return''}
function pointInRing(pt,ring){let inside=false;for(let i=0,j=ring.length-1;i<ring.length;j=i++){const [xi,yi]=ring[i],[xj,yj]=ring[j];const hit=((yi>pt[1])!==(yj>pt[1]))&&(pt[0]<(xj-xi)*(pt[1]-yi)/((yj-yi)||1e-12)+xi);if(hit)inside=!inside}return inside}
function pointInGeom(pt,g){if(!g)return false;const poly=r=>r.length&&pointInRing(pt,r[0])&&!r.slice(1).some(h=>pointInRing(pt,h));if(g.type==='Polygon')return poly(g.coordinates);if(g.type==='MultiPolygon')return g.coordinates.some(poly);return false}
function zoneOf(f){const m=midpoint(f);if(m&&st.zones?.features){for(const z of st.zones.features){if(pointInGeom([m.lng,m.lat],z.geometry)){const n=zoneFromProps(z.properties);if(n)return n}}}return zoneFromProps(f.properties)}
function category(f){const p=f.properties||{},r=low(p.restrictio||p.restriction),s=low(p.spacetype);if(r.includes('no parking')||r.includes('reserved')||r.includes('loading')||r.includes('ada')||s.includes('ada'))return'no';if(r.includes('permit')||zoneOf(f))return'permit';if(r.includes('$')||r.includes('paid')||r.includes('payment')||r.includes('meter'))return'paid';if(r.includes('time')||r.includes('hour')||r.includes('min'))return'timed';if(r.includes('free'))return'free';return'mixed'}
function graceNow(){const d=new Date(),m=d.getMonth()+1,day=d.getDate();return(m===7&&day>=15)||m===8}
function eligible(f){const c=category(f),sel=$('zone').value,z=zoneOf(f);if(c==='no')return false;if(c==='permit'){if(!$('permit').checked)return false;if(sel!=='none')return z===sel;return graceNow()}if(c==='free')return $('free').checked;return $('paid').checked}
function enrich(){if(!st.parking)return;for(const f of st.parking.features){f.properties=f.properties||{};f.properties._cat=category(f);f.properties._zone=zoneOf(f);f.properties._eligible=eligible(f)?1:0}}
function selectedZoneGeo(){const z=$('zone').value;if(z==='none'||!st.zones)return{type:'FeatureCollection',features:[]};return{type:'FeatureCollection',features:st.zones.features.filter(f=>zoneFromProps(f.properties)===z)}}
function refreshMapData(){if(!st.mapReady||!st.parking)return;enrich();map.getSource('parking')?.setData(st.parking);map.getSource('zones')?.setData(selectedZoneGeo());const eligibleCount=st.parking.features.filter(f=>f.properties._eligible===1).length;const z=$('zone').value;const permitCount=st.parking.features.filter(f=>f.properties._cat==='permit'&&(z==='none'||f.properties._zone===z)).length;$('dataStat').textContent=z==='none'?`${eligibleCount} eligible curbs`:`Zone ${z}: ${permitCount} permit · ${eligibleCount} eligible`}
function addDataLayers(){if(map.getSource('parking'))return;map.addSource('zones',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'zone-fill',type:'fill',source:'zones',paint:{'fill-color':'#a989ff','fill-opacity':.10}});map.addLayer({id:'zone-line',type:'line',source:'zones',paint:{'line-color':'#a989ff','line-width':3,'line-opacity':.85}});map.addSource('parking',{type:'geojson',data:st.parking||{type:'FeatureCollection',features:[]}});map.addLayer({id:'parking-lines',type:'line',source:'parking',paint:{'line-color':['match',['get','_cat'],'free',COLORS.free,'permit',COLORS.permit,'paid',COLORS.paid,'timed',COLORS.timed,'mixed',COLORS.mixed,COLORS.no],'line-width':['case',['==',['get','_eligible'],1],6,2],'line-opacity':['case',['==',['get','_eligible'],1],.92,.08]},layout:{'line-cap':'round','line-join':'round'}});map.addSource('route',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'route-casing',type:'line',source:'route',paint:{'line-color':'#ffffff','line-width':10,'line-opacity':.8},layout:{'line-cap':'round','line-join':'round'}});map.addLayer({id:'route-line',type:'line',source:'route',paint:{'line-color':'#2878ff','line-width':7,'line-opacity':.95},layout:{'line-cap':'round','line-join':'round'}});map.addSource('current-curb',{type:'geojson',data:{type:'FeatureCollection',features:[]}});map.addLayer({id:'current-curb-line',type:'line',source:'current-curb',paint:{'line-color':'#2caf76','line-width':11,'line-opacity':1},layout:{'line-cap':'round','line-join':'round'}});map.on('click','parking-lines',e=>{const f=e.features?.[0];if(!f)return;const p=f.properties||{};new maplibregl.Popup().setLngLat(e.lngLat).setHTML(`<strong>${nameOf(f)}</strong><br>${p.restrictio||p._cat||'parking'}${p._zone?` · Zone ${p._zone}`:''}${p.spaces?` · ${p.spaces} mapped spaces`:''}<br><small>Always verify posted signs.</small>`).addTo(map)});map.on('mouseenter','parking-lines',()=>map.getCanvas().style.cursor='pointer');map.on('mouseleave','parking-lines',()=>map.getCanvas().style.cursor='')}
async function getJSON(url,opts){const r=await fetch(url,opts);if(!r.ok){let detail='';try{detail=(await r.json()).error||''}catch{}throw new Error(detail||`${r.status}`)}return r.json()}
async function loadData(){try{const [p,z]=await Promise.all([getJSON('/api/parking'),getJSON('/api/zones').catch(()=>null)]);st.parking=p;st.zones=z;enrich();if(st.mapReady){addDataLayers();refreshMapData()}note(z?'Gainesville parking and permit zones loaded.':'Parking loaded; zone polygons unavailable.')}catch(e){$('dataStat').textContent='GIS load failed';note(`Parking GIS failed: ${e.message}`,7000)}}
function markerEl(cls,text=''){const el=document.createElement('div');el.className=cls;if(text)el.textContent=text;return el}
function setDestinationMarker(){st.destMarker?.remove();st.destMarker=new maplibregl.Marker({element:markerEl('destpin')}).setLngLat([st.dest.lng,st.dest.lat]).addTo(map)}
function updateUser(pos,center=false){st.user={lat:pos.coords.latitude,lng:pos.coords.longitude,heading:Number.isFinite(pos.coords.heading)?pos.coords.heading:null,accuracy:pos.coords.accuracy};$('gpsStat').textContent=`GPS ±${Math.round(pos.coords.accuracy)}m`;if(!st.userMarker)st.userMarker=new maplibregl.Marker({element:markerEl('puck'),rotationAlignment:'map'}).setLngLat([st.user.lng,st.user.lat]).addTo(map);else st.userMarker.setLngLat([st.user.lng,st.user.lat]);if(center)map.easeTo({center:[st.user.lng,st.user.lat],zoom:17,pitch:42,duration:700})}
function requestGPS(center=true){return new Promise((resolve,reject)=>{if(!navigator.geolocation){note('This browser does not support GPS.');return reject(new Error('gps'))}navigator.geolocation.getCurrentPosition(p=>{updateUser(p,center);resolve(p)},e=>{note(!window.isSecureContext?'GPS requires HTTPS. Open the Vercel URL.':'Location permission is unavailable or denied.',7000);reject(e)},{enableHighAccuracy:true,timeout:12000,maximumAge:1500})})}
function rankSegments(){if(!st.parking)return[];return st.parking.features.filter(eligible).map(f=>({f,m:midpoint(f),e:endpoints(f)})).filter(x=>x.m&&x.e&&hav(st.dest,x.m)<5000).sort((a,b)=>hav(st.dest,a.m)-hav(st.dest,b.m))}
function orderSegments(items,n,start){const pool=items.slice(0,140),out=[],used=new Set;let cur=start;while(out.length<Math.min(n,pool.length)){let best=-1,score=Infinity;pool.forEach((x,i)=>{if(used.has(i))return;const d=hav(cur,x.m)+hav(st.dest,x.m)*.16;if(d<score){score=d;best=i}});if(best<0)break;const x=pool[best],entry=hav(cur,x.e.a)<=hav(cur,x.e.b)?x.e.a:x.e.b,exit=entry===x.e.a?x.e.b:x.e.a;out.push({...x,entry,exit});used.add(best);cur=exit}return out}
async function routeRequest(points){return getJSON('/api/route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({locations:points.map(p=>({lat:p.lat,lon:p.lng}))})})}
function mergeLines(lines){const coords=[];for(const l of lines){const c=l?.geometry?.coordinates||[];if(!c.length)continue;if(coords.length&&coords.at(-1)[0]===c[0][0]&&coords.at(-1)[1]===c[0][1])coords.push(...c.slice(1));else coords.push(...c)}return{type:'Feature',properties:{},geometry:{type:'LineString',coordinates:coords}}}
function setRouteGeo(feature){st.routeGeometry=feature;map.getSource('route')?.setData(feature||{type:'FeatureCollection',features:[]})}
function clearRoute(){setRouteGeo({type:'FeatureCollection',features:[]});map.getSource('current-curb')?.setData({type:'FeatureCollection',features:[]});for(const m of st.numberMarkers)m.remove();st.numberMarkers=[];st.route=[];st.idx=0;$('start').disabled=$('next').disabled=$('found').disabled=true;$('list').innerHTML='';$('routeStat').textContent='No route'}
function fitRoute(feature){const c=feature?.geometry?.coordinates||[];if(!c.length)return;const b=new maplibregl.LngLatBounds();c.forEach(p=>b.extend(p));map.fitBounds(b,{padding:{top:120,bottom:220,left:40,right:40},maxZoom:16,duration:900})}
function renderRouteList(){const rows=st.route.slice(0,12).map((x,i)=>`<div class="route-item"><strong>${i+1}. ${nameOf(x.f)}</strong><span>${x.f.properties?._cat||category(x.f)}${zoneOf(x.f)?` · Zone ${zoneOf(x.f)}`:''}</span></div>`).join('');$('list').innerHTML=rows}
function updateCurrentCurb(){const x=st.route[st.idx];if(!x)return;map.getSource('current-curb')?.setData(x.f);$('status').innerHTML=`<b>Segment ${st.idx+1}/${st.route.length}:</b> ${nameOf(x.f)}. Drive from the entry end to the exit end and scan the highlighted curb.`;$('navMain').textContent=`Next: ${nameOf(x.f)}`;$('navSub').textContent=`Parking segment ${st.idx+1} of ${st.route.length}`}
